namespace InstituteManagement.Application.Features.Finance;

public sealed record StudentPaymentDto(
    Guid Id,
    string FinancialAccountCode,
    string PaymentCode,
    Guid StudentId,
    string StudentCode,
    string PublicId,
    string StudentName,
    string Department,
    string EnrollmentCode,
    int YearLevel,
    string Shift,
    string AcademicYear,
    string Semester,
    decimal TuitionFee,
    decimal OtherFee,
    decimal AdjustmentAmount,
    string AdjustmentReason,
    decimal TotalDue,
    decimal TotalPaid,
    decimal Balance,
    decimal AmountDue,
    string Currency,
    DateOnly DueOn,
    string Status,
    string ConfirmationMethod,
    DateTime? PaidAtUtc,
    DateTime? ReminderSentAtUtc,
    DateTime? ReminderReadAtUtc,
    string TimetableStatus,
    string PeriodState,
    string QrPayload,
    IReadOnlyList<FinancialPaymentDto> Payments,
    DateTime CreateAt);

public sealed record FinancialPaymentDto(
    Guid Id,
    string PaymentCode,
    decimal Amount,
    string Method,
    string Status,
    string TransactionReference,
    DateTime PaidAtUtc,
    DateTime CreateAt);
