import type { InstituteSettings } from "./administration-types";

const csv = (...values: string[]) => values.join(",");

export const defaultSettings: InstituteSettings = {
  institute: {
    name: "Institude of New Khmer",
    shortName: "INK",
    code: "INK",
    establishedYear: "2018",
    description: "The academic management platform for Institude of New Khmer.",
    logoUrl: "/branding/ink-logo.png",
    faviconUrl: "/icon.png",
    email: "info@ink.edu.kh",
    phone: "+855 23 555 888",
    mobile: "+855 12 555 888",
    website: "https://www.ink.edu.kh",
    country: "Cambodia",
    city: "Phnom Penh",
    province: "Phnom Penh",
    district: "Sen Sok",
    address: "Street 1986, Sangkat Phnom Penh Thmey, Khan Sen Sok, Phnom Penh",
    postalCode: "12101",
  },
  "academic-year": {
    currentYear: "2026–2027",
    code: "AY2026",
    startsOn: "2026-09-01",
    endsOn: "2027-08-31",
    status: "Active",
  },
  semester: {
    currentTerm: "Semester 1",
    startsOn: "2026-09-01",
    endsOn: "2027-01-31",
    semester1Name: "Semester 1",
    semester1Code: "SEM1",
    semester1StartsOn: "2026-09-01",
    semester1EndsOn: "2027-01-31",
    semester1Status: "Active",
    semester2Name: "Semester 2",
    semester2Code: "SEM2",
    semester2StartsOn: "2027-02-01",
    semester2EndsOn: "2027-06-30",
    semester2Status: "Upcoming",
    summerName: "Summer Term",
    summerCode: "SUMMER",
    summerStartsOn: "2027-07-01",
    summerEndsOn: "2027-08-31",
    summerStatus: "Upcoming",
  },
  departments: {
    codePrefix: "DEP",
    codeIncludeYear: "false",
    codeStartingNumber: "1",
    codePaddingWidth: "4",
    codeSeparator: "-",
    defaultStatus: "Active",
    requireDepartmentHead: "true",
    allowCrossDepartmentTeaching: "false",
  },
  courses: {
    codePrefix: "CRS",
    codeIncludeYear: "false",
    codeStartingNumber: "1",
    codePaddingWidth: "4",
    codeSeparator: "-",
    defaultCapacity: "40",
    requireAssignedTeacher: "true",
  },
  classrooms: {
    codePrefix: "ROOM",
    codeIncludeYear: "false",
    codeStartingNumber: "1",
    codePaddingWidth: "4",
    codeSeparator: "-",
    defaultCapacity: "40",
    attendanceDeviceRequired: "true",
  },
  "users-access": {
    defaultUserStatus: "Active",
    userStatuses: csv("Active", "Inactive", "Suspended", "Pending", "Locked"),
    availableRoles: csv("Super Administrator", "Administrator", "Teacher", "Staff", "Student"),
    permissionCatalog: csv(
      "Dashboard",
      "View Students", "Create Students", "Edit Students", "Delete Students",
      "View Teachers", "Create Teachers", "Edit Teachers", "Delete Teachers",
      "View Courses", "Create Courses", "Edit Courses", "Delete Courses",
      "View Attendance", "Create Attendance", "Edit Attendance",
      "View Grades", "Create Grades", "Edit Grades", "Publish Grades",
      "Manage Users", "Manage Roles", "Manage Settings", "View System Logs",
    ),
  },
  "student-rules": {
    idPrefix: "STU",
    includeYear: "true",
    startingNumber: "1",
    paddingWidth: "4",
    separator: "-",
    requireApplication: "true",
    requireDocuments: "true",
    allowLateEnrollment: "true",
    lateEnrollmentDays: "14",
    requireEnrollmentApproval: "true",
    maximumCoursesPerSemester: "6",
    statuses: csv("Applicant", "Active", "Inactive", "Suspended", "Graduated", "Withdrawn", "Expelled"),
    requiredInformation: csv("fullName", "dateOfBirth", "gender", "phone", "email", "address", "emergencyContact", "profilePhoto", "identificationDocument", "previousEducation"),
  },
  "teacher-rules": {
    idPrefix: "TCH",
    includeYear: "true",
    startingNumber: "1",
    paddingWidth: "4",
    separator: "-",
    statuses: csv("Active", "Inactive", "On Leave", "Suspended", "Terminated"),
    maximumCourses: "4",
    maximumClasses: "6",
    allowMultipleDepartments: "true",
    requireDepartmentAssignment: "true",
    requireCourseAssignment: "true",
  },
  "attendance-rules": {
    method: "ID Card",
    attendanceRequired: "true",
    checkInRequired: "true",
    checkOutRequired: "false",
    teacherCanRecord: "true",
    studentCanView: "true",
    onTimeThresholdMinutes: "14",
    lateThresholdMinutes: "15",
    veryLateThresholdMinutes: "30",
    absentAfterMinutes: "30",
    excusedAbsenceEnabled: "true",
    requireExcuseApproval: "true",
    maximumExcusedAbsences: "10",
    teacherCanEdit: "true",
    allowCorrection: "true",
    correctionPeriodDays: "7",
    requireAdminApproval: "true",
    keepChangeHistory: "true",
    requireCorrectionReason: "true",
    autoAbsent: "true",
    autoPercentage: "true",
    notifyTeacher: "true",
    notifyAdministrator: "true",
  },
  "grade-rules": {
    gradingSystem: "Percentage + Letter Grade",
    minimumScore: "0",
    maximumScore: "100",
    passMark: "50",
    gpaEnabled: "true",
    maximumGpa: "4.00",
    aPlusMinimum: "95",
    aMinimum: "90",
    bPlusMinimum: "85",
    bMinimum: "80",
    cPlusMinimum: "75",
    cMinimum: "70",
    dMinimum: "60",
    aPlusGpa: "4.00",
    aGpa: "4.00",
    bPlusGpa: "3.50",
    bGpa: "3.00",
    cPlusGpa: "2.50",
    cGpa: "2.00",
    dGpa: "1.00",
    fGpa: "0.00",
    overallPassMark: "50",
    coursePassMark: "50",
    finalExamMinimum: "40",
    gpaScale: "4.00",
    includeFailedCourses: "true",
    includeWithdrawnCourses: "false",
    gpaDecimalPlaces: "2",
  },
  notifications: {
    notificationCodePrefix: "NOT",
    announcementCodePrefix: "ANN",
    historyCodePrefix: "NHS",
    codeIncludeYear: "false",
    codeStartingNumber: "1",
    codePaddingWidth: "8",
    codeSeparator: "-",
    emailEnabled: "true",
    smtpHost: "smtp.ink.edu.kh",
    smtpPort: "587",
    emailEncryption: "TLS",
    senderName: "Institude of New Khmer",
    senderEmail: "noreply@ink.edu.kh",
    smsEnabled: "false",
    smsProvider: "None",
    smsSenderId: "INK",
    inAppEnabled: "true",
    studentNotifications: "true",
    teacherNotifications: "true",
    staffNotifications: "true",
    administratorNotifications: "true",
    enabledTemplates: csv("Student Enrollment Confirmation", "Course Enrollment", "Attendance Alert", "Grade Published", "Password Reset", "Account Created", "Announcement", "Academic Year Started"),
    attendanceAlerts: "true",
    deviceAlerts: "true",
    gradeReminders: "true",
    dailySummary: "true",
  },
  system: {
    language: "English",
    availableLanguages: csv("English", "Khmer"),
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24 Hour",
    timeZone: "Asia/Phnom_Penh",
    firstDayOfWeek: "Monday",
    autoRefreshSeconds: "30",
    maintenanceEnabled: "false",
    maintenanceMessage: "System is currently under maintenance. Please try again later.",
    allowAdministratorsDuringMaintenance: "true",
    loggingEnabled: "true",
    loginLogs: "true",
    userActivityLogs: "true",
    securityLogs: "true",
    configurationChangeLogs: "true",
    logRetentionDays: "90",
  },
  security: {
    passwordMinimumLength: "8",
    requireUppercase: "true",
    requireLowercase: "true",
    requireNumber: "true",
    requireSpecialCharacter: "true",
    passwordExpirationDays: "90",
    preventPasswordReuse: "5",
    administratorSessionMinutes: "30",
    staffSessionMinutes: "60",
    teacherSessionMinutes: "60",
    studentSessionMinutes: "120",
    rememberMeEnabled: "true",
    maximumLoginAttempts: "5",
    lockoutDurationMinutes: "15",
    resetAttemptCounterMinutes: "30",
    logFailedAttempts: "true",
    twoFactorMode: "Optional",
    administratorTwoFactor: "Required",
    staffTwoFactor: "Optional",
    teacherTwoFactor: "Optional",
    studentTwoFactor: "Optional",
    twoFactorMethods: csv("Authenticator App", "Email OTP"),
  },
};
