using InstituteManagement.Application.Features.Administration;
using InstituteManagement.Application.Features.Attendance;
using InstituteManagement.Application.Features.Dashboard;
using InstituteManagement.Application.Features.Enrollment;
using InstituteManagement.Application.Features.Enrollment.Classrooms;
using InstituteManagement.Application.Features.Enrollment.Courses;
using InstituteManagement.Application.Features.Enrollment.Departments;
using InstituteManagement.Application.Features.Enrollment.Students;
using InstituteManagement.Application.Features.Enrollment.Teachers;
using InstituteManagement.Application.Features.Enrollment.Timetable;
using InstituteManagement.Application.Features.Grades;
using InstituteManagement.Application.Features.History;
using InstituteManagement.Application.Features.Management.Classrooms;
using InstituteManagement.Application.Features.Management.Courses;
using InstituteManagement.Application.Features.Management.Departments;
using InstituteManagement.Application.Features.Management.Students;
using InstituteManagement.Application.Features.Management.Teachers;
using InstituteManagement.Application.Features.Notifications.Announcements;
using InstituteManagement.Application.Features.Notifications.History;
using InstituteManagement.Application.Features.Notifications.Notifications;
using InstituteManagement.Application.Features.Operations;
using InstituteManagement.Application.Features.Record;
using InstituteManagement.Application.Features.Results;
using InstituteManagement.Application.Features.Timetable;
using InstituteManagement.Infrastructure.Persistence;
using InstituteManagement.Infrastructure.Services.Administration;
using InstituteManagement.Infrastructure.Services.Attendance;
using InstituteManagement.Infrastructure.Services.Common;
using InstituteManagement.Infrastructure.Services.Dashboard;
using InstituteManagement.Infrastructure.Services.Enrollment;
using InstituteManagement.Infrastructure.Services.Enrollment.Classrooms;
using InstituteManagement.Infrastructure.Services.Enrollment.Courses;
using InstituteManagement.Infrastructure.Services.Enrollment.Departments;
using InstituteManagement.Infrastructure.Services.Enrollment.Students;
using InstituteManagement.Infrastructure.Services.Enrollment.Teachers;
using InstituteManagement.Infrastructure.Services.Enrollment.Timetable;
using InstituteManagement.Infrastructure.Services.History;
using InstituteManagement.Infrastructure.Services.Grades;
using InstituteManagement.Infrastructure.Services.Management;
using InstituteManagement.Infrastructure.Services.Management.Classrooms;
using InstituteManagement.Infrastructure.Services.Management.Courses;
using InstituteManagement.Infrastructure.Services.Management.Departments;
using InstituteManagement.Infrastructure.Services.Management.Students;
using InstituteManagement.Infrastructure.Services.Management.Teachers;
using InstituteManagement.Infrastructure.Services.Notifications.Announcements;
using InstituteManagement.Infrastructure.Services.Notifications.History;
using InstituteManagement.Infrastructure.Services.Notifications.Notifications;
using InstituteManagement.Infrastructure.Services.Operations;
using InstituteManagement.Infrastructure.Services.Record;
using InstituteManagement.Infrastructure.Services.Results;
using InstituteManagement.Infrastructure.Services.Timetable;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using StackExchange.Redis;

namespace InstituteManagement.Infrastructure;

public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services, IConfiguration configuration)
    {
        if (bool.TryParse(configuration["Database:UseInMemory"], out var useInMemory) && useInMemory)
            services.AddDbContext<InstituteDbContext>(options => options.UseInMemoryDatabase("InstituteManagement"));
        else
        {
            services.AddDbContext<InstituteDbContext>(options => options.UseSqlServer(configuration.GetConnectionString("Database"), sql => sql.EnableRetryOnFailure()));
            var redisConnection = configuration.GetConnectionString("Redis");
            if (!string.IsNullOrWhiteSpace(redisConnection))
                services.AddSingleton<IConnectionMultiplexer>(_ => ConnectionMultiplexer.Connect(redisConnection));
        }

        services.AddScoped<InstituteCache>();
        services.AddScoped<IDashboardQueryService, DashboardQueryService>();
        services.AddScoped<EnrollmentSettingsReader>();
        services.AddScoped<EnrollmentChangeCommitter>();
        services.AddScoped<StudentEnrollmentReader>();
        services.AddScoped<StudentEnrollmentEditor>();
        services.AddScoped<StudentEnrollmentRecordSynchronizer>();
        services.AddScoped<IStudentEnrollmentService, StudentEnrollmentService>();
        services.AddScoped<TeacherAssignmentReader>();
        services.AddScoped<TeacherAssignmentPolicy>();
        services.AddScoped<TeacherAssignmentEditor>();
        services.AddScoped<ITeacherAssignmentService, TeacherEnrollmentService>();
        services.AddScoped<CourseAssignmentReader>();
        services.AddScoped<CourseAssignmentPolicy>();
        services.AddScoped<CourseAssignmentEditor>();
        services.AddScoped<ICourseAssignmentService, CourseEnrollmentService>();
        services.AddScoped<ClassroomAssignmentReader>();
        services.AddScoped<ClassroomAssignmentEditor>();
        services.AddScoped<IClassroomAssignmentService, ClassroomEnrollmentService>();
        services.AddScoped<IDepartmentEnrollmentService, DepartmentEnrollmentService>();
        services.AddScoped<TimetableScheduleEditor>();
        services.AddScoped<TimetableEnrollmentReader>();
        services.AddScoped<TimetableEnrollmentValidator>();
        services.AddScoped<TimetableEnrollmentEditor>();
        services.AddScoped<ITimetableEnrollmentService, TimetableEnrollmentService>();
        services.AddScoped<IOperationQueryService, OperationQueryService>();
        services.AddScoped<OperationContextService>();
        services.AddScoped<OperationEnrollmentPeriodService>();
        services.AddScoped<IOperationModuleReader, DashboardOperationReader>();
        services.AddScoped<IOperationModuleReader, StudentOperationReader>();
        services.AddScoped<IOperationModuleReader, TeacherOperationReader>();
        services.AddScoped<IOperationModuleReader, ClassroomOperationReader>();
        services.AddScoped<IOperationModuleReader, CourseOperationReader>();
        services.AddScoped<IOperationModuleReader, TimetableOperationReader>();
        services.AddScoped<IOperationalRecordQueryService, OperationalRecordQueryService>();
        services.AddScoped<IOperationalRecordEditService, OperationalRecordEditService>();
        services.AddScoped<ClassSessionRecorderService>();
        services.AddHostedService<ClassSessionRecorderHostedService>();
        services.AddScoped<IOperationalRecordReader, StudentOperationalRecordReader>();
        services.AddScoped<IOperationalRecordReader, TeacherOperationalRecordReader>();
        services.AddScoped<IOperationalRecordReader, ClassroomOperationalRecordReader>();
        services.AddScoped<IOperationalRecordReader, CourseOperationalRecordReader>();
        services.AddScoped<IOperationalRecordReader, ClassSessionOperationalRecordReader>();
        services.AddScoped<IOperationalRecordReader, DepartmentOperationalRecordReader>();
        services.AddScoped<IOperationalRecordReader, TimetableOperationalRecordReader>();
        services.AddScoped<IHistoryQueryService, HistoryQueryService>();
        services.AddScoped<IResultQueryService, ResultQueryService>();
        services.AddScoped<IHistorySnapshotProvider, StudentHistorySnapshotProvider>();
        services.AddScoped<IHistorySnapshotProvider, TeacherHistorySnapshotProvider>();
        services.AddScoped<IHistorySnapshotProvider, ClassroomHistorySnapshotProvider>();
        services.AddScoped<IHistorySnapshotProvider, CourseHistorySnapshotProvider>();
        services.AddScoped<IHistorySnapshotProvider, TimetableHistorySnapshotProvider>();
        services.AddScoped<IHistorySnapshotProvider, AttendanceHistorySnapshotProvider>();
        services.AddScoped<IHistorySnapshotProvider, DepartmentHistorySnapshotProvider>();
        services.AddScoped<IHistorySnapshotProvider, GradeHistorySnapshotProvider>();
        services.AddScoped<ISettingsService, SettingsService>();
        services.AddScoped<AnnouncementPolicy>();
        services.AddScoped<IAnnouncementService, AnnouncementService>();
        services.AddScoped<INotificationService, NotificationService>();
        services.AddScoped<INotificationHistoryService, NotificationHistoryService>();
        services.AddScoped<AcademicCalendarClock>();
        services.AddScoped<StudentAcademicYearAdvancer>();
        services.AddScoped<ActivePeriodLedgerCreator>();
        services.AddScoped<AcademicCalendarRolloverService>();
        services.AddHostedService<AcademicCalendarHostedService>();
        services.AddScoped<IAttendanceService, AttendanceService>();
        services.AddScoped<IGradeService, GradeService>();
        services.AddScoped<IStudentManagementService, StudentManagementService>();
        services.AddScoped<ITeacherManagementService, TeacherManagementService>();
        services.AddScoped<IClassroomManagementService, ClassroomManagementService>();
        services.AddScoped<ICourseManagementService, CourseManagementService>();
        services.AddScoped<IDepartmentManagementService, DepartmentManagementService>();
        services.AddScoped<ITimetableCatalogService, TimetableCatalogService>();
        services.AddScoped<IAttendanceCatalogService, AttendanceCatalogService>();
        services.AddScoped<IGradeCatalogService, GradeCatalogService>();
        return services;
    }
}
