"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";
import { useInstituteSettings } from "@/features/administration/institute-settings-context";
import { managementApis } from "../management-apis";
import { managementCopy, managementFields, moduleDefaults } from "../management-config";
import { relationshipCode } from "../management-id";
import type { Field, ManagementItem, ManagementModule, References } from "../management-types";
import { validateManagementFields, validationMessages, type FieldErrors } from "../management-validation";
import { relationshipCreateTarget } from "../relationship-create";
import { EditorField } from "./editor-field";

type PersonEditorMode = "full" | "profile" | "enrollment";
const studentProfileFields = new Set(["photoDataUrl", "studentCode", "name", "email"]);
const studentEnrollmentFields = new Set(["departmentId", "year", "shift"]);
const teacherProfileFields = new Set(["photoDataUrl", "teacherCode", "name", "email"]);
const teacherEnrollmentFields = new Set(["departmentId"]);
const autoGeneratedCodeFields: Partial<Record<ManagementModule, string>> = {
  students: "studentCode",
  teachers: "teacherCode",
  departments: "departmentCode",
  courses: "courseCode",
  classrooms: "classroomCode",
};

export function ManagementEditor({ module, item, references, scopeDepartmentId, scopeYear, studentMode = "full", teacherMode = "full", onClose, onSaved }: { module: Exclude<ManagementModule, "overview">; item: ManagementItem | null; references: References; scopeDepartmentId: string; scopeYear: string; studentMode?: PersonEditorMode; teacherMode?: PersonEditorMode; onClose: () => void; onSaved: () => void }) {
  const router = useRouter();
  const { settings } = useInstituteSettings();
  const defaults = moduleDefaults(module, scopeDepartmentId);
  if (scopeYear && module === "students") defaults.year = scopeYear;
  if (module === "departments") defaults.status = settings.departments.defaultStatus || defaults.status;
  if (module === "courses") defaults.capacity = settings.courses.defaultCapacity || defaults.capacity;
  if (module === "classrooms") { defaults.capacity = settings.classrooms.defaultCapacity || defaults.capacity; defaults.deviceOnline = settings.classrooms.attendanceDeviceRequired === "true" ? "true" : defaults.deviceOnline; }
  if (module === "attendance") defaults.method = settings["attendance-rules"].method || defaults.method;
  if (module === "grades") defaults.term = settings.semester.currentTerm || defaults.term;
  const [values, setValues] = useState<Record<string, string>>(item ? { ...defaults, ...item.values } : defaults);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({});
  const saveController = useRef<AbortController | null>(null);
  const configuredFields = managementFields[module].filter(field =>
    (module !== "students" || studentMode === "full" || (studentMode === "profile" ? studentProfileFields : studentEnrollmentFields).has(field.key)) &&
    (module !== "teachers" || teacherMode === "full" || (teacherMode === "profile" ? teacherProfileFields : teacherEnrollmentFields).has(field.key))
  ).map(field => {
    if (!item && autoGeneratedCodeFields[module] === field.key) return { ...field, label: `${field.label} (auto if blank)`, required: false };
    if (field.key === "teacherId" && module === "courses") return { ...field, required: settings.courses.requireAssignedTeacher === "true" };
    if (field.key === "headTeacherId" && module === "departments") return { ...field, required: settings.departments.requireDepartmentHead === "true" };
    if (field.key === "term" && module === "grades") return { ...field, options: Array.from(new Set([settings.semester.currentTerm, ...(field.options ?? [])].filter(Boolean))) };
    return field;
  });
  const fields: Field[] = [...configuredFields, ...(module === "attendance" && item && settings["attendance-rules"].requireCorrectionReason === "true"
    ? [{ key: "correctionReason", label: "Correction reason", required: true } satisfies Field]
    : [])];

  function optionsFor(field: Field) {
    if (field.options) return field.options.map(value => ({ id: value, label: value }));
    if (!field.source) return [];
    const source: ManagementItem[] = references[field.source];
    const allowCrossDepartmentTeacher = field.source === "teachers" && module === "courses" && settings.departments.allowCrossDepartmentTeaching === "true";
    const scoped = ["teachers", "students", "classrooms", "courses"].includes(field.source) && values.departmentId && !allowCrossDepartmentTeacher
      ? source.filter(option => option.values.departmentId === values.departmentId || (field.source === "teachers" && module === "courses" && !option.values.departmentId))
      : source;
    return scoped.filter(option => option.values.status !== "Inactive" && (field.source !== "students" || !scopeYear || option.values.year === scopeYear)).map(option => ({
      id: option.id,
      label: `${relationshipCode(field.source!, option.values)} - ${option.values.name ?? option.values.building ?? option.values.student ?? option.values.course}`,
      detail: [option.values.roomType, option.values.department].filter(Boolean).join(" - "),
    }));
  }

  async function save(event: React.FormEvent) {
    event.preventDefault();
    const optionSets = Object.fromEntries(fields.filter(field => field.type === "select").map(field => [field.key, new Set(optionsFor(field).map(option => option.id))]));
    const nextErrors = validateManagementFields(fields, values, optionSets);
    setFieldErrors(nextErrors);
    setError("");
    if (Object.keys(nextErrors).length) return;

    setSaving(true);
    const controller = new AbortController();
    saveController.current = controller;
    try {
      if (item) await managementApis[module].update(item.id, values, controller.signal);
      else await managementApis[module].create(values, controller.signal);
      onSaved();
    } catch (reason) {
      if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Could not save this record.");
      setSaving(false);
    } finally {
      if (saveController.current === controller) saveController.current = null;
    }
  }

  function change(field: Field, value: string) {
    setValues(current => ({ ...current, [field.key]: value }));
    setFieldErrors(current => { const next = { ...current }; delete next[field.key]; return next; });
    setError("");
  }

  function cancel() {
    saveController.current?.abort();
    onClose();
  }

  function createOptionFor(field: Field) {
    const target = relationshipCreateTarget(field.source);
    if (!target) return undefined;
    return { id: `create-${field.source}`, label: target.label, action: () => { cancel(); router.push(target.path); } };
  }

  const problems = validationMessages(fieldErrors, error);
  const personMode = module === "students" ? studentMode : module === "teachers" ? teacherMode : "full";
  const personName = module === "teachers" ? "teacher" : "student";
  const editTitle = personMode === "enrollment" ? `Edit ${personName} enrollment` : personMode === "profile" ? `Edit ${personName} profile` : `Edit ${managementCopy[module].singular}`;
  const editorEyebrow = personMode === "enrollment" ? "Academic enrollment" : item ? "Personal data management" : "New current data";
  const editorDescription = personMode === "enrollment"
    ? module === "teachers" ? "Change the teacher's assigned department. Active course and department-head relationships must remain consistent." : "Change only the student's department, year level, and learning shift. A department or year change reassigns the current course ledger."
    : "Required profile data and Administration rules are validated before saving.";
  const saveLabel = personMode === "enrollment" ? "Save enrollment" : personMode === "profile" ? "Save profile" : item ? "Save changes" : `Add ${managementCopy[module].singular}`;
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) cancel(); }}><form noValidate className="modal management-modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">{editorEyebrow}</span><h2>{item ? editTitle : `Add ${managementCopy[module].singular}`}</h2><p>{editorDescription}</p></div><button type="button" className="icon-button" onClick={cancel}><Icon name="close"/></button></div><div className="management-form-grid">{fields.map(field => <EditorField key={field.key} field={field} value={values[field.key] ?? ""} options={optionsFor(field)} createOption={createOptionFor(field)} error={fieldErrors[field.key]} onChange={value => change(field, value)}/>)}</div>{problems.length > 0 && <div className="form-error validation-summary" role="alert"><strong>Fix these problems:</strong><ul>{problems.map(problem => <li key={problem}>{problem}</li>)}</ul></div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={cancel}>{saving ? "Cancel request" : "Cancel"}</button><button className="button primary" disabled={saving}>{saving ? "Saving relationships..." : saveLabel}</button></div></form></div>;
}
