// <auto-generated />
using System;
using InstituteManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstituteManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InstituteDbContext))]
    [Migration("20260929014755_Phase2DatabaseArchitecture")]
    partial class Phase2DatabaseArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnnouncementCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementCode")
                        .IsUnique();

                    b.HasIndex("NotificationId")
                        .IsUnique()
                        .HasFilter("[NotificationId] IS NOT NULL");

                    b.HasIndex("IsActive", "CreateAt");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AttendanceCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<TimeOnly?>("CheckedInAt")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("StudentEnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceCode")
                        .IsUnique();

                    b.HasIndex("Date");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Date"), new[] { "StudentId", "Status", "CheckedInAt" });

                    b.HasIndex("StudentEnrollmentId", "Date")
                        .IsUnique();

                    b.HasIndex("StudentEnrollmentId", "StudentId");

                    b.HasIndex("AcademicYear", "Term", "CreateAt")
                        .IsDescending(false, false, true);

                    b.HasIndex("StudentId", "AcademicYear", "Term", "Date");

                    b.ToTable("AttendanceRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceRecords_Status", "[Status] IN (N'Present', N'Late', N'Absent', N'Excused', N'Permission')");
                        });
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AuditLogCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogCode")
                        .IsUnique();

                    b.HasIndex("CreateAt")
                        .IsDescending();

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreateAt"), new[] { "Action", "Subject", "Type" });

                    b.HasIndex("ResourceId");

                    b.HasIndex("Type", "CreateAt");

                    b.HasIndex("Type", "Action", "ResourceId")
                        .HasFilter("[ResourceId] IS NOT NULL");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassPermissionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("SessionDate", "Status");

                    b.HasIndex("StudentId", "SessionDate")
                        .IsUnique();

                    b.ToTable("ClassPermissionRequests", "Attendance");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AbsentCount")
                        .HasColumnType("int");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ClassSessionRecordCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClassroomCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndsAt")
                        .HasColumnType("time");

                    b.Property<int>("ExcusedCount")
                        .HasColumnType("int");

                    b.Property<int>("LateCount")
                        .HasColumnType("int");

                    b.Property<int>("PresentCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ScheduleEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.Property<string>("TeacherAttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassSessionRecordCode")
                        .IsUnique();

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SessionDate");

                    b.HasIndex("TeacherId");

                    b.HasIndex("AcademicYear", "Term");

                    b.HasIndex("DepartmentId", "YearLevel");

                    b.HasIndex("ScheduleEntryId", "SessionDate")
                        .IsUnique();

                    b.ToTable("ClassSessionRecords");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassSessionStart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid>("ScheduleEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("ScheduleEntryId", "SessionDate")
                        .IsUnique();

                    b.HasIndex("TeacherId", "SessionDate");

                    b.ToTable("ClassSessionStarts", "Attendance");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassSessionStudentAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckedInAt")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("ClassSessionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("StudentEnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassSessionRecordId", "StudentId")
                        .IsUnique();

                    b.HasIndex("StudentEnrollmentId", "ClassSessionRecordId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StudentEnrollmentId", "ClassSessionRecordId"), new[] { "StudentId", "Status", "CheckedInAt" });

                    b.HasIndex("StudentEnrollmentId", "StudentId");

                    b.HasIndex("StudentId", "ClassSessionRecordId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StudentId", "ClassSessionRecordId"), new[] { "Status", "CheckedInAt" });

                    b.ToTable("ClassSessionStudentAttendance", "Record", t =>
                        {
                            t.HasCheckConstraint("CK_ClassSessionStudentAttendance_Status", "[Status] IN (N'Present', N'Late', N'Absent', N'Excused', N'Permission', N'Class not held', N'Not recorded')");
                        });
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ClassroomCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DeviceOnline")
                        .HasColumnType("bit");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomCode")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassroomAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnrollmentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HistoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ClassroomId", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("EnrollmentCode", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("AcademicYear", "Semester", "Status", "DepartmentId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AcademicYear", "Semester", "Status", "DepartmentId"), new[] { "ClassroomId", "EnrollmentCode" });

                    b.ToTable("ClassroomAssignments", "Enrollment");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Semester 1");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("YearLevel", "Semester");

                    b.HasIndex("DepartmentId", "YearLevel", "Semester", "CourseCode");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DepartmentId", "YearLevel", "Semester", "CourseCode"), new[] { "Name", "IsActive", "TeacherId" });

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.CourseAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnrollmentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HistoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("DepartmentId", "YearLevel");

                    b.HasIndex("CourseId", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("EnrollmentCode", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("AcademicYear", "Semester", "Status", "DepartmentId", "YearLevel");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AcademicYear", "Semester", "Status", "DepartmentId", "YearLevel"), new[] { "CourseId", "TeacherId", "EnrollmentCode" });

                    b.ToTable("CourseAssignments", "Enrollment");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("HeadTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.HasIndex("HeadTeacherId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("AdjustmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AdjustmentReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BakongMd5")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BakongQrPayload")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal?>("DeclaredAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeclaredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinancialAccountCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("LatePenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LatePenaltyDays")
                        .HasColumnType("int");

                    b.Property<decimal>("OtherFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentPlan")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("QrExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("QrGeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReminderReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReminderSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("StudentEnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("TuitionFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentEnrollmentId")
                        .IsUnique();

                    b.HasIndex("StudentEnrollmentId", "StudentId")
                        .IsUnique();

                    b.HasIndex("FinancialAccountCode", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("StudentId", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("AcademicYear", "Semester", "Status", "ClosedAtUtc", "DueOn");

                    b.ToTable("FinancialAccounts", "Finance", t =>
                        {
                            t.HasCheckConstraint("CK_FinancialAccounts_Amounts", "[TuitionFee] >= 0 AND [OtherFee] >= 0 AND [LatePenaltyDays] >= 0 AND [LatePenaltyAmount] >= 0 AND ([DeclaredAmount] IS NULL OR [DeclaredAmount] >= 0)");

                            t.HasCheckConstraint("CK_FinancialAccounts_Closure", "[ClosedAtUtc] IS NULL OR [Status] = N'Paid'");

                            t.HasCheckConstraint("CK_FinancialAccounts_Status", "[Status] IN (N'Pending', N'Partial', N'Paid', N'Refunded', N'Cancelled')");
                        });
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.FinancialPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid>("FinancialAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCode")
                        .IsUnique();

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasFilter("[TransactionReference] <> ''");

                    b.HasIndex("FinancialAccountId", "Status", "PaidAtUtc");

                    b.ToTable("Payments", "Finance", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payments_Status", "[Status] IN (N'Completed', N'Cancelled', N'Refunded')");
                        });
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.GradeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("AssignmentMaximum")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AssignmentScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AttendanceMaximum")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AttendanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<decimal>("FinalExamMaximum")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FinalExamScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LetterGrade")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("MidtermMaximum")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MidtermScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ReviewNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("StudentEnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubmissionVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubmittedByTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GradeCode")
                        .IsUnique();

                    b.HasIndex("SubmittedByTeacherId");

                    b.HasIndex("UpdatedAtUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UpdatedAtUtc"), new[] { "Score" });

                    b.HasIndex("AcademicYear", "Term");

                    b.HasIndex("StudentEnrollmentId", "CourseId")
                        .IsUnique();

                    b.HasIndex("StudentEnrollmentId", "StudentId");

                    b.HasIndex("FinalizedAtUtc", "AcademicYear", "Term");

                    b.HasIndex("ReviewStatus", "AcademicYear", "Term");

                    b.HasIndex("StudentId", "AcademicYear", "Term");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StudentId", "AcademicYear", "Term"), new[] { "CourseId", "Score", "LetterGrade", "ReviewStatus", "FinalizedAtUtc" });

                    b.HasIndex("CourseId", "AcademicYear", "Term", "ReviewStatus");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CourseId", "AcademicYear", "Term", "ReviewStatus"), new[] { "StudentId", "Score", "FinalizedAtUtc" });

                    b.HasIndex("StudentId", "CourseId", "AcademicYear", "Term")
                        .IsUnique();

                    b.ToTable("GradeRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_GradeRecords_ReviewStatus", "[ReviewStatus] IN (N'Pending', N'SubmissionRequested', N'SubmissionAuthorized', N'Submitted', N'Approved', N'Rejected', N'ResubmitRequested', N'ResubmitAuthorized')");

                            t.HasCheckConstraint("CK_GradeRecords_Scores", "[AttendanceScore] >= 0 AND [AttendanceMaximum] > 0 AND [AssignmentScore] >= 0 AND [AssignmentMaximum] > 0 AND [MidtermScore] >= 0 AND [MidtermMaximum] > 0 AND [FinalExamScore] >= 0 AND [FinalExamMaximum] > 0 AND [Score] >= 0");
                        });
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NotificationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NotificationCode")
                        .IsUnique();

                    b.HasIndex("IsRead", "CreateAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.NotificationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NotificationHistoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NotificationHistoryCode")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.HasIndex("Kind", "CreateAt");

                    b.ToTable("NotificationHistory");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ScheduleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndsAt")
                        .HasColumnType("time");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Morning");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimetableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TimetableCode")
                        .IsUnique();

                    b.HasIndex("DayOfWeek", "StartsAt", "EndsAt");

                    b.HasIndex("ClassroomId", "DayOfWeek", "StartsAt", "EndsAt");

                    b.HasIndex("TeacherId", "DayOfWeek", "StartsAt", "EndsAt");

                    b.ToTable("ScheduleEntries");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.SemesterResultPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentEnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtUtc");

                    b.HasIndex("StudentEnrollmentId")
                        .IsUnique();

                    b.HasIndex("StudentEnrollmentId", "StudentId");

                    b.HasIndex("StudentId", "AcademicYear", "Term")
                        .IsUnique();

                    b.ToTable("SemesterResultPublications", "Grades");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoDataUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("[PublicId] <> ''");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "StudentCode");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DepartmentId", "StudentCode"), new[] { "FullName", "YearLevel", "Status" });

                    b.ToTable("Students");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.StudentAcademicEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("EnrollmentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentCode")
                        .IsUnique();

                    b.HasIndex("StudentId", "Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StudentId", "Status"), new[] { "EnrollmentCode", "StartedAtUtc", "CompletedAtUtc" });

                    b.ToTable("StudentAcademicEnrollments", "Enrollment", t =>
                        {
                            t.HasCheckConstraint("CK_StudentAcademicEnrollments_Completion", "([Status] = N'Active' AND [CompletedAtUtc] IS NULL) OR ([Status] <> N'Active' AND [CompletedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_StudentAcademicEnrollments_Status", "[Status] IN (N'Active', N'Completed', N'Cancelled')");
                        });
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.StudentEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnrollmentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FinanceCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HistoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("StudentAcademicEnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinanceCode")
                        .IsUnique()
                        .HasFilter("[FinanceCode] <> ''");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("[PublicId] <> ''");

                    b.HasIndex("ResultCode")
                        .IsUnique()
                        .HasFilter("[ResultCode] <> ''");

                    b.HasIndex("DepartmentId", "YearLevel");

                    b.HasIndex("EnrollmentCode", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("StudentAcademicEnrollmentId", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("StudentId", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("AcademicYear", "Semester", "Status", "Shift", "DepartmentId", "YearLevel");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AcademicYear", "Semester", "Status", "Shift", "DepartmentId", "YearLevel"), new[] { "StudentId", "EnrollmentCode" });

                    b.ToTable("EnrollmentSemesters", "Enrollment", t =>
                        {
                            t.HasCheckConstraint("CK_EnrollmentSemesters_Semester", "[Semester] IN (N'Semester 1', N'Semester 2', N'Summer Term')");

                            t.HasCheckConstraint("CK_EnrollmentSemesters_Status", "[Status] IN (N'Active', N'Paused', N'Completed', N'Removed')");

                            t.HasCheckConstraint("CK_EnrollmentSemesters_YearLevel", "[YearLevel] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SystemSettingCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("SystemSettingCode")
                        .IsUnique();

                    b.HasIndex("Section", "Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoDataUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TeacherCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("[PublicId] <> ''");

                    b.HasIndex("TeacherCode")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "TeacherCode");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DepartmentId", "TeacherCode"), new[] { "FullName", "Status" });

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.TeacherAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnrollmentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HistoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("[PublicId] <> ''");

                    b.HasIndex("EnrollmentCode", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("TeacherId", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("AcademicYear", "Semester", "Status", "DepartmentId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AcademicYear", "Semester", "Status", "DepartmentId"), new[] { "TeacherId", "EnrollmentCode" });

                    b.ToTable("TeacherAssignments", "Enrollment");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.TimetableEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("EnrollmentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HistoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ScheduleEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("AcademicYear", "Semester", "Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AcademicYear", "Semester", "Status"), new[] { "ScheduleEntryId", "EnrollmentCode" });

                    b.HasIndex("EnrollmentCode", "AcademicYear", "Semester")
                        .IsUnique();

                    b.HasIndex("ScheduleEntryId", "AcademicYear", "Semester")
                        .IsUnique();

                    b.ToTable("TimetableEnrollments", "Enrollment");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Notification", "Notification")
                        .WithOne()
                        .HasForeignKey("InstituteManagement.Domain.Entities.Announcement", "NotificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.StudentEnrollment", "StudentEnrollment")
                        .WithMany()
                        .HasForeignKey("StudentEnrollmentId", "StudentId")
                        .HasPrincipalKey("Id", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentEnrollment");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassPermissionRequest", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassSessionRecord", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.ScheduleEntry", "ScheduleEntry")
                        .WithMany()
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("ScheduleEntry");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassSessionStart", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.ScheduleEntry", "ScheduleEntry")
                        .WithMany()
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScheduleEntry");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassSessionStudentAttendance", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.ClassSessionRecord", "ClassSessionRecord")
                        .WithMany("StudentAttendance")
                        .HasForeignKey("ClassSessionRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.StudentEnrollment", "StudentEnrollment")
                        .WithMany()
                        .HasForeignKey("StudentEnrollmentId", "StudentId")
                        .HasPrincipalKey("Id", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassSessionRecord");

                    b.Navigation("Student");

                    b.Navigation("StudentEnrollment");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Classroom", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassroomAssignment", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Classroom");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Course", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.CourseAssignment", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Department");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Department", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "HeadTeacher")
                        .WithMany()
                        .HasForeignKey("HeadTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HeadTeacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.FinancialAccount", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.StudentEnrollment", "StudentEnrollment")
                        .WithOne()
                        .HasForeignKey("InstituteManagement.Domain.Entities.FinancialAccount", "StudentEnrollmentId", "StudentId")
                        .HasPrincipalKey("InstituteManagement.Domain.Entities.StudentEnrollment", "Id", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentEnrollment");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.FinancialPayment", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.FinancialAccount", "FinancialAccount")
                        .WithMany("Payments")
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinancialAccount");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.GradeRecord", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "SubmittedByTeacher")
                        .WithMany()
                        .HasForeignKey("SubmittedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InstituteManagement.Domain.Entities.StudentEnrollment", "StudentEnrollment")
                        .WithMany()
                        .HasForeignKey("StudentEnrollmentId", "StudentId")
                        .HasPrincipalKey("Id", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("StudentEnrollment");

                    b.Navigation("SubmittedByTeacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ScheduleEntry", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InstituteManagement.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.SemesterResultPublication", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.StudentEnrollment", "StudentEnrollment")
                        .WithMany()
                        .HasForeignKey("StudentEnrollmentId", "StudentId")
                        .HasPrincipalKey("Id", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentEnrollment");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Student", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.StudentAcademicEnrollment", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.StudentEnrollment", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.StudentAcademicEnrollment", "StudentAcademicEnrollment")
                        .WithMany("Semesters")
                        .HasForeignKey("StudentAcademicEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Student");

                    b.Navigation("StudentAcademicEnrollment");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.TeacherAssignment", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.TimetableEnrollment", b =>
                {
                    b.HasOne("InstituteManagement.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.ScheduleEntry", "ScheduleEntry")
                        .WithMany()
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstituteManagement.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("ScheduleEntry");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.ClassSessionRecord", b =>
                {
                    b.Navigation("StudentAttendance");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.FinancialAccount", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("InstituteManagement.Domain.Entities.StudentAcademicEnrollment", b =>
                {
                    b.Navigation("Semesters");
                });
#pragma warning restore 612, 618
        }
    }
}
