namespace InstituteManagement.Application.Features.Administration.Settings;

public static partial class SettingsCatalog
{
    private static readonly SettingsSectionDefinition AttendanceRulesSection = Section("attendance-rules",
        Boolean("attendanceRequired", true),
        Boolean("checkInRequired", true),
        Boolean("checkOutRequired", false),
        Boolean("teacherCanRecord", false),
        Boolean("studentCanView", true),
        Option("method", "ID Card", "Manual", "ID Card", "QR Code", "Biometric"),
        Integer("onTimeThresholdMinutes", "14", 0, 1440),
        Integer("lateThresholdMinutes", "15", 0, 1440),
        Integer("veryLateThresholdMinutes", "30", 0, 1440),
        Integer("absentAfterMinutes", "30", 0, 1440),
        Boolean("autoAbsent", true),
        Boolean("autoPercentage", true),
        Decimal("absentScoreDeduction", "2", 0, 100),
        Decimal("permissionScoreDeduction", "0.91", 0, 100),
        Integer("retakeAbsentSections", "6", 0, 10000),
        Integer("failAbsentSections", "8", 0, 10000),
        Integer("retakePermissionSections", "12", 0, 10000),
        Integer("failPermissionSections", "14", 0, 10000),
        Boolean("excusedAbsenceEnabled", true),
        Boolean("requireExcuseApproval", true),
        Integer("maximumExcusedAbsences", "10", 0, 365),
        Boolean("teacherCanEdit", false),
        Boolean("allowCorrection", true),
        Integer("correctionPeriodDays", "7", 0, 365),
        Boolean("requireAdminApproval", true),
        Boolean("requireCorrectionReason", true),
        Boolean("keepChangeHistory", true),
        Boolean("notifyTeacher", true),
        Boolean("notifyAdministrator", true));

    private static readonly SettingsSectionDefinition GradeRulesSection = Section("grade-rules",
        Option("gradingSystem", "Percentage + Letter Grade", "Percentage + Letter Grade"),
        Decimal("maximumScore", "100", 1, 1000),
        Decimal("minimumScore", "0", 0, 999),
        Decimal("passMark", "50", 0, 1000),
        Boolean("gpaEnabled", true),
        Decimal("maximumGpa", "4.00", 0, 10),
        Decimal("attendanceWeight", "10", 0, 100),
        Decimal("assignmentWeight", "20", 0, 100),
        Decimal("midtermWeight", "20", 0, 100),
        Decimal("finalExamWeight", "50", 0, 100),
        Integer("expectedCourseCount", "5", 1, 100),
        Option("semesterCalculation", "Average of course totals", "Average of course totals"),
        Decimal("aMinimum", "90", 0, 1000),
        Decimal("bMinimum", "80", 0, 1000),
        Decimal("cMinimum", "70", 0, 1000),
        Decimal("dMinimum", "60", 0, 1000),
        Decimal("eMinimum", "50", 0, 1000),
        Decimal("aGpa", "4.00", 0, 10),
        Decimal("bGpa", "3.00", 0, 10),
        Decimal("cGpa", "2.00", 0, 10),
        Decimal("dGpa", "1.00", 0, 10),
        Decimal("eGpa", "0.50", 0, 10),
        Decimal("fGpa", "0.00", 0, 10),
        Decimal("overallPassMark", "50", 0, 1000),
        Decimal("coursePassMark", "50", 0, 1000),
        Decimal("finalExamMinimum", "40", 0, 1000),
        Decimal("gpaScale", "4.00", 0, 10),
        Boolean("includeFailedCourses", true),
        Boolean("includeWithdrawnCourses", false),
        Integer("gpaDecimalPlaces", "2", 0, 6));
}
