namespace InstituteManagement.Application.Features.Administration.Settings;

public static partial class SettingsCatalog
{
    private static readonly SettingsSectionDefinition AttendanceRulesSection = Section("attendance-rules",
        Boolean("attendanceRequired", true),
        Boolean("checkInRequired", true),
        Boolean("checkOutRequired", false),
        Boolean("teacherCanRecord", true),
        Boolean("studentCanView", true),
        Option("method", "ID Card", "Manual", "ID Card", "QR Code", "Biometric"),
        Integer("onTimeThresholdMinutes", "14", 0, 1440),
        Integer("lateThresholdMinutes", "15", 0, 1440),
        Integer("veryLateThresholdMinutes", "30", 0, 1440),
        Integer("absentAfterMinutes", "30", 0, 1440),
        Boolean("autoAbsent", true),
        Boolean("autoPercentage", true),
        Boolean("excusedAbsenceEnabled", true),
        Boolean("requireExcuseApproval", true),
        Integer("maximumExcusedAbsences", "10", 0, 365),
        Boolean("teacherCanEdit", true),
        Boolean("allowCorrection", true),
        Integer("correctionPeriodDays", "7", 0, 365),
        Boolean("requireAdminApproval", true),
        Boolean("requireCorrectionReason", true),
        Boolean("keepChangeHistory", true),
        Boolean("notifyTeacher", true),
        Boolean("notifyAdministrator", true));

    private static readonly SettingsSectionDefinition GradeRulesSection = Section("grade-rules",
        Option("gradingSystem", "Percentage + Letter Grade", "Percentage + Letter Grade"),
        Decimal("maximumScore", "100", 1, 1000),
        Decimal("minimumScore", "0", 0, 999),
        Decimal("passMark", "50", 0, 1000),
        Boolean("gpaEnabled", true),
        Decimal("maximumGpa", "4.00", 0, 10),
        Decimal("aPlusMinimum", "95", 0, 1000),
        Decimal("aMinimum", "90", 0, 1000),
        Decimal("bPlusMinimum", "85", 0, 1000),
        Decimal("bMinimum", "80", 0, 1000),
        Decimal("cPlusMinimum", "75", 0, 1000),
        Decimal("cMinimum", "70", 0, 1000),
        Decimal("dMinimum", "60", 0, 1000),
        Decimal("aPlusGpa", "4.00", 0, 10),
        Decimal("aGpa", "4.00", 0, 10),
        Decimal("bPlusGpa", "3.50", 0, 10),
        Decimal("bGpa", "3.00", 0, 10),
        Decimal("cPlusGpa", "2.50", 0, 10),
        Decimal("cGpa", "2.00", 0, 10),
        Decimal("dGpa", "1.00", 0, 10),
        Decimal("fGpa", "0.00", 0, 10),
        Decimal("overallPassMark", "50", 0, 1000),
        Decimal("coursePassMark", "50", 0, 1000),
        Decimal("finalExamMinimum", "40", 0, 1000),
        Decimal("gpaScale", "4.00", 0, 10),
        Boolean("includeFailedCourses", true),
        Boolean("includeWithdrawnCourses", false),
        Integer("gpaDecimalPlaces", "2", 0, 6));
}
