namespace InstituteManagement.Application.Features.Administration.Settings;

public static partial class SettingsCatalog
{
    private const string NotificationTemplates = "Student Enrollment Confirmation,Course Enrollment,Attendance Alert,Grade Published,Password Reset,Account Created,Announcement,Academic Year Started";

    private static readonly SettingsSectionDefinition NotificationsSection = Section("notifications",
        Code("notificationCodePrefix", "NOT", 16),
        Code("historyCodePrefix", "NHS", 16),
        Boolean("codeIncludeYear", false),
        Digits("codeStartingNumber", "1", 12),
        Integer("codePaddingWidth", "8", 1, 12),
        Option("codeSeparator", "-", "-", "/", "."),
        Boolean("attendanceAlerts", true),
        Boolean("deviceAlerts", true),
        Boolean("gradeReminders", true),
        Boolean("dailySummary", true),
        Boolean("emailEnabled", true),
        OptionalText("smtpHost", "smtp.ink.edu.kh", 255),
        OptionalInteger("smtpPort", "587", 1, 65535),
        OptionalOption("emailEncryption", "TLS", "None", "TLS", "SSL"),
        OptionalText("senderName", "Institude of New Khmer", 200),
        OptionalEmail("senderEmail", "noreply@ink.edu.kh"),
        Boolean("smsEnabled", false),
        Text("smsProvider", "None", 100),
        OptionalCode("smsSenderId", "INK", 32),
        Boolean("inAppEnabled", true),
        Boolean("studentNotifications", true),
        Boolean("teacherNotifications", true),
        Boolean("staffNotifications", true),
        Boolean("administratorNotifications", true),
        OptionalList("enabledTemplates", NotificationTemplates));

    private static readonly SettingsSectionDefinition SystemSection = Section("system",
        Option("language", "English", "English", "Khmer"),
        List("availableLanguages", "English,Khmer"),
        Option("dateFormat", "DD/MM/YYYY", "DD/MM/YYYY", "MM/DD/YYYY", "YYYY-MM-DD", "DD MMM YYYY"),
        Option("timeFormat", "24 Hour", "12 Hour", "24 Hour"),
        TimeZone("timeZone", "Asia/Phnom_Penh"),
        Option("firstDayOfWeek", "Monday", "Monday", "Sunday"),
        Integer("autoRefreshSeconds", "30", 5, 3600),
        Boolean("maintenanceEnabled", false),
        Text("maintenanceMessage", "System is currently under maintenance. Please try again later.", 1000),
        Boolean("allowAdministratorsDuringMaintenance", true),
        Boolean("loggingEnabled", true),
        Boolean("loginLogs", true),
        Boolean("userActivityLogs", true),
        Boolean("securityLogs", true),
        Boolean("configurationChangeLogs", true),
        Integer("logRetentionDays", "90", 1, 3650));

    private static readonly SettingsSectionDefinition SecuritySection = Section("security",
        Integer("passwordMinimumLength", "8", 6, 128),
        Boolean("requireUppercase", true),
        Boolean("requireLowercase", true),
        Boolean("requireNumber", true),
        Boolean("requireSpecialCharacter", true),
        Integer("passwordExpirationDays", "90", 0, 3650),
        Integer("preventPasswordReuse", "5", 0, 100),
        Integer("administratorSessionMinutes", "30", 1, 10080),
        Integer("staffSessionMinutes", "60", 1, 10080),
        Integer("teacherSessionMinutes", "60", 1, 10080),
        Integer("studentSessionMinutes", "120", 1, 10080),
        Boolean("rememberMeEnabled", true),
        Integer("maximumLoginAttempts", "5", 1, 100),
        Integer("lockoutDurationMinutes", "15", 1, 10080),
        Integer("resetAttemptCounterMinutes", "30", 1, 10080),
        Boolean("logFailedAttempts", true),
        Option("twoFactorMode", "Optional", "Disabled", "Optional", "Required"),
        Option("administratorTwoFactor", "Required", "Disabled", "Optional", "Required"),
        Option("staffTwoFactor", "Optional", "Disabled", "Optional", "Required"),
        Option("teacherTwoFactor", "Optional", "Disabled", "Optional", "Required"),
        Option("studentTwoFactor", "Optional", "Disabled", "Optional", "Required"),
        List("twoFactorMethods", "Authenticator App,Email OTP"));
}
