"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { useRouter, useSearchParams } from "next/navigation";
import { api } from "@/lib/api";
import type { CatalogItem } from "@/lib/types";
import { ErrorPage, LoadingPage, PageHeading } from "./page-primitives";
import { Icon } from "./icon";

type Module = "overview" | "students" | "teachers" | "classrooms" | "courses" | "timetable" | "attendance" | "departments" | "grades";
type Field = { key: string; label: string; type?: "text" | "email" | "number" | "select" | "photo" | "date" | "time" | "checkbox"; source?: keyof References; options?: string[]; required?: boolean };
type References = { departments: CatalogItem[]; teachers: CatalogItem[]; students: CatalogItem[]; classrooms: CatalogItem[]; courses: CatalogItem[] };

const emptyReferences: References = { departments: [], teachers: [], students: [], classrooms: [], courses: [] };
const copy: Record<Module, { title: string; description: string; singular: string }> = {
  overview: { title: "Institute management", description: "Manage current institute data through connected department workspaces.", singular: "item" },
  students: { title: "Student management", description: "Enroll students, maintain 4×6 profile photos, and assign each learner to a department.", singular: "student" },
  teachers: { title: "Teacher management", description: "Maintain faculty profiles, availability, department membership, and leadership eligibility.", singular: "teacher" },
  classrooms: { title: "Classroom management", description: "Assign rooms to departments and manage capacity, availability, and device state.", singular: "classroom" },
  courses: { title: "Course management", description: "Connect courses to departments and eligible teachers with capacity and credit rules.", singular: "course" },
  timetable: { title: "Timetable planner", description: "Schedule a department’s course, teacher, and classroom together without broken relationships.", singular: "class" },
  attendance: { title: "Attendance management", description: "Record and correct current attendance while preserving each change in immutable history.", singular: "attendance entry" },
  departments: { title: "Department management", description: "Organize academic units and appoint an existing teacher as each department head.", singular: "department" },
  grades: { title: "Grade management", description: "Maintain department gradebooks by connecting students to courses and terms.", singular: "grade" },
};

const fields: Record<Exclude<Module, "overview">, Field[]> = {
  students: [{ key: "photoDataUrl", label: "4×6 student photo", type: "photo", required: true }, { key: "number", label: "Student ID", required: true }, { key: "name", label: "Full name", required: true }, { key: "email", label: "Email", type: "email", required: true }, { key: "departmentId", label: "Department", type: "select", source: "departments", required: true }, { key: "year", label: "Year level", type: "number", required: true }, { key: "status", label: "Status", type: "select", options: ["Active", "Inactive"], required: true }],
  teachers: [{ key: "photoDataUrl", label: "4×6 teacher photo", type: "photo", required: true }, { key: "number", label: "Teacher ID", required: true }, { key: "name", label: "Full name", required: true }, { key: "email", label: "Email", type: "email", required: true }, { key: "departmentId", label: "Department", type: "select", source: "departments", required: true }, { key: "status", label: "Work status", type: "select", options: ["Available", "Teaching", "Meeting", "On leave", "Inactive"], required: true }],
  classrooms: [{ key: "code", label: "Room code", required: true }, { key: "building", label: "Building", required: true }, { key: "departmentId", label: "Department", type: "select", source: "departments", required: true }, { key: "capacity", label: "Capacity", type: "number", required: true }, { key: "status", label: "Room status", type: "select", options: ["Available", "Running", "Starting", "Offline", "Inactive"], required: true }, { key: "deviceOnline", label: "Attendance device online", type: "checkbox" }],
  courses: [{ key: "code", label: "Course code", required: true }, { key: "name", label: "Course name", required: true }, { key: "departmentId", label: "Department", type: "select", source: "departments", required: true }, { key: "teacherId", label: "Assigned teacher", type: "select", source: "teachers", required: true }, { key: "credits", label: "Credits", type: "number", required: true }, { key: "capacity", label: "Student capacity", type: "number", required: true }, { key: "status", label: "Status", type: "select", options: ["Active", "Inactive"], required: true }],
  timetable: [{ key: "courseId", label: "Course", type: "select", source: "courses", required: true }, { key: "teacherId", label: "Teacher", type: "select", source: "teachers", required: true }, { key: "classroomId", label: "Classroom", type: "select", source: "classrooms", required: true }, { key: "dayOfWeek", label: "Day", type: "select", options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], required: true }, { key: "startsAt", label: "Starts at", type: "time", required: true }, { key: "endsAt", label: "Ends at", type: "time", required: true }, { key: "status", label: "Status", type: "select", options: ["Upcoming", "Running", "Completed", "Cancelled"], required: true }],
  attendance: [{ key: "studentId", label: "Student", type: "select", source: "students", required: true }, { key: "date", label: "Attendance date", type: "date", required: true }, { key: "checkedInAt", label: "Check-in time", type: "time" }, { key: "status", label: "Status", type: "select", options: ["Present", "Late", "Absent", "Excused"], required: true }, { key: "method", label: "Method", type: "select", options: ["ID Card", "Manual", "QR Code", "Biometric"], required: true }],
  departments: [{ key: "code", label: "Department code", required: true }, { key: "name", label: "Department name", required: true }, { key: "headTeacherId", label: "Head of department", type: "select", source: "teachers", required: true }, { key: "status", label: "Status", type: "select", options: ["Active", "Inactive"], required: true }],
  grades: [{ key: "studentId", label: "Student", type: "select", source: "students", required: true }, { key: "courseId", label: "Course", type: "select", source: "courses", required: true }, { key: "score", label: "Score", type: "number", required: true }, { key: "term", label: "Semester / term", type: "select", options: ["Semester 1", "Semester 2", "Summer"], required: true }],
};

export function ManagementWorkspace({ module: rawModule }: { module: string }) {
  const currentModule = (rawModule in copy ? rawModule : "overview") as Module;
  const router = useRouter(); const searchParams = useSearchParams(); const routeDepartmentId = searchParams.get("departmentId") ?? "";
  const [items, setItems] = useState<CatalogItem[]>([]); const [references, setReferences] = useState<References>(emptyReferences);
  const departmentId = routeDepartmentId; const [query, setQuery] = useState(""); const [error, setError] = useState(false); const [actionError, setActionError] = useState(""); const [ready, setReady] = useState(false); const [editing, setEditing] = useState<CatalogItem | null | undefined>();

  const loadReferences = useCallback(() => Promise.all([api.catalog("departments"), api.catalog("teachers"), api.catalog("students"), api.catalog("classrooms"), api.catalog("courses")]).then(([departments, teachers, students, classrooms, courses]) => setReferences({ departments, teachers, students, classrooms, courses })).catch(() => setError(true)), []);
  const load = useCallback(() => {
    const resource = currentModule === "overview" ? "departments" : currentModule;
    api.catalog(resource, query, departmentId).then(result => { setItems(result); setReady(true); }).catch(() => setError(true));
  }, [departmentId, currentModule, query]);
  useEffect(() => { loadReferences(); }, [loadReferences]);
  useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer); }, [load]);

  const selectedDepartment = references.departments.find(x => x.id === departmentId);
  const activeItems = useMemo(() => items.filter(item => item.values.status !== "Inactive" && item.values.status !== "Cancelled"), [items]);
  if (error) return <ErrorPage retry={() => { setError(false); loadReferences(); load(); }}/>;
  if (!ready) return <LoadingPage/>;

  return <>
    <PageHeading eyebrow="Current data management" title={copy[currentModule].title} description={copy[currentModule].description} actions={currentModule !== "overview" ? <button className="button primary" onClick={() => setEditing(null)}><Icon name="plus" size={16}/> Add {copy[currentModule].singular}</button> : undefined}/>
    <section className="management-toolbar panel management-toolbar-global">
      {currentModule !== "overview" && <label className="management-search"><Icon name="search" size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder={`Search ${currentModule}…`}/></label>}
      <div className="management-scope"><span>Current scope</span><strong>{selectedDepartment?.values.name ?? "Whole institute"}</strong></div>
      <div className="management-total"><span>Active records</span><strong>{activeItems.length}</strong></div>
    </section>
    {actionError && <section className="management-rule-error"><Icon name="bell" size={16}/><div><strong>Relationship protected</strong><span>{actionError}</span></div><button onClick={() => setActionError("")}>Dismiss</button></section>}
    {currentModule === "overview" ? <ManagementOverview references={references} onSelect={value => router.push(`/management/students?departmentId=${encodeURIComponent(value)}`)} selected={departmentId}/> : <ModuleLayout module={currentModule} items={items} references={references} onEdit={setEditing} onDeactivate={async item => { if (confirm(`Deactivate or remove this ${copy[currentModule].singular}? Its history will remain read-only.`)) { setActionError(""); try { await api.remove(currentModule, item.id); load(); loadReferences(); } catch (reason) { setActionError(reason instanceof Error ? reason.message : "This record is still used by another active record."); } } }}/>} 
    {editing !== undefined && currentModule !== "overview" && <ManagementEditor module={currentModule} item={editing} references={references} scopeDepartmentId={departmentId} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); load(); loadReferences(); }}/>} 
  </>;
}

function ManagementOverview({ references, onSelect, selected }: { references: References; onSelect: (id: string) => void; selected: string }) {
  return <section className="department-overview-grid">{references.departments.filter(department => !selected || department.id === selected).map(department => {
    const teachers = references.teachers.filter(x => x.values.departmentId === department.id); const students = references.students.filter(x => x.values.departmentId === department.id); const courses = references.courses.filter(x => x.values.departmentId === department.id); const rooms = references.classrooms.filter(x => x.values.departmentId === department.id);
    return <article className={`department-overview-card panel ${selected === department.id ? "selected" : ""}`} key={department.id}><div className="department-code-cell"><strong>{department.values.code}</strong><span>Department</span></div><div className="department-overview-head"><div><span>Academic department</span><h2>{department.values.name}</h2></div></div><div className="hod-line"><span>Head of department</span><strong>{department.values.head || "Not appointed"}</strong></div><div className="relationship-counts"><div><strong>{students.length}</strong><span>Students</span></div><div><strong>{teachers.length}</strong><span>Teachers</span></div><div><strong>{courses.length}</strong><span>Courses</span></div><div><strong>{rooms.length}</strong><span>Rooms</span></div></div><span className={`table-status ${department.values.status.toLowerCase()}`}>{department.values.status}</span><button className="button secondary" onClick={() => onSelect(department.id)}>Open department <Icon name="arrow" size={14}/></button></article>;
  })}</section>;
}

function ModuleLayout({ module, items, references, onEdit, onDeactivate }: { module: Exclude<Module, "overview">; items: CatalogItem[]; references: References; onEdit: (item: CatalogItem) => void; onDeactivate: (item: CatalogItem) => void }) {
  if (module === "students" || module === "teachers") return <PeopleRoster type={module} items={items} onEdit={onEdit} onDeactivate={onDeactivate}/>;
  if (module === "classrooms") return <RoomBoard items={items} onEdit={onEdit} onDeactivate={onDeactivate}/>;
  if (module === "courses") return <CourseBoard items={items} onEdit={onEdit} onDeactivate={onDeactivate}/>;
  if (module === "timetable") return <TimetableBoard items={items} onEdit={onEdit} onDeactivate={onDeactivate}/>;
  if (module === "attendance") return <AttendanceDesk items={items} onEdit={onEdit} onDeactivate={onDeactivate}/>;
  if (module === "departments") return <DepartmentDirectory items={items} references={references} onEdit={onEdit} onDeactivate={onDeactivate}/>;
  return <Gradebook items={items} onEdit={onEdit} onDeactivate={onDeactivate}/>;
}

function Actions({ item, onEdit, onDeactivate }: { item: CatalogItem; onEdit: (item: CatalogItem) => void; onDeactivate: (item: CatalogItem) => void }) { return <div className="management-actions"><button onClick={() => onEdit(item)}>Edit</button><button className="danger" onClick={() => onDeactivate(item)}>Deactivate</button></div>; }

function PeopleRoster({ type, items, onEdit, onDeactivate }: { type: "students" | "teachers"; items: CatalogItem[]; onEdit: (item: CatalogItem) => void; onDeactivate: (item: CatalogItem) => void }) { return <section className={`panel horizontal-management-table people-horizontal ${type}-horizontal`}><div className="horizontal-management-head"><span>Photo</span><span>{type === "students" ? "Student" : "Teacher"} identity</span><span>Contact</span><span>Department</span><span>{type === "students" ? "Academic level" : "Faculty type"}</span><span>Status</span><span>Actions</span></div>{items.map(item => <article className="horizontal-management-row" key={item.id}><div className="horizontal-portrait"><Image unoptimized width={40} height={60} src={item.values.photoDataUrl} alt={`${item.values.name} 4 by 6 profile`}/></div><div className="horizontal-primary"><strong>{item.values.name}</strong><span>{item.values.number}</span></div><div className="horizontal-detail"><span>Email address</span><strong>{item.values.email}</strong></div><div className="horizontal-detail"><span>Assigned department</span><strong>{item.values.department}</strong></div><div className="horizontal-detail"><span>{type === "students" ? "Year level" : "Relationship"}</span><strong>{type === "students" ? `Year ${item.values.year}` : "Faculty member"}</strong></div><span className={`table-status ${item.values.status.toLowerCase().replace(" ", "-")}`}>{item.values.status}</span><Actions item={item} onEdit={onEdit} onDeactivate={onDeactivate}/></article>)}</section>; }
function RoomBoard({ items, onEdit, onDeactivate }: LayoutProps) { return <section className="panel horizontal-management-table room-horizontal"><div className="horizontal-management-head"><span>Room</span><span>Building</span><span>Department ownership</span><span>Capacity</span><span>Attendance device</span><span>Status</span><span>Actions</span></div>{items.map(item => <article className="horizontal-management-row" key={item.id}><div className="room-code-horizontal">{item.values.code}</div><div className="horizontal-detail"><span>Building</span><strong>{item.values.building}</strong></div><div className="horizontal-detail"><span>Assigned department</span><strong>{item.values.department}</strong></div><div className="horizontal-detail"><span>Maximum occupancy</span><strong>{item.values.capacity} seats</strong></div><div className="device-detail"><i className={item.values.deviceOnline === "true" ? "online" : ""}/><strong>{item.values.deviceOnline === "true" ? "Online" : "Offline"}</strong></div><span className={`table-status ${item.values.status.toLowerCase()}`}>{item.values.status}</span><Actions item={item} onEdit={onEdit} onDeactivate={onDeactivate}/></article>)}</section>; }
function CourseBoard({ items, onEdit, onDeactivate }: LayoutProps) { return <section className="panel horizontal-management-table course-horizontal"><div className="horizontal-management-head"><span>Code</span><span>Course</span><span>Department</span><span>Assigned teacher</span><span>Credits</span><span>Capacity</span><span>Status</span><span>Actions</span></div>{items.map(item => <article className="horizontal-management-row" key={item.id}><div className="course-code">{item.values.code}</div><div className="horizontal-primary"><strong>{item.values.name}</strong><span>Active curriculum course</span></div><div className="horizontal-detail"><span>Owning department</span><strong>{item.values.department}</strong></div><div className="horizontal-detail"><span>Teacher relationship</span><strong>{item.values.teacher}</strong></div><div className="relationship-number"><strong>{item.values.credits}</strong><span>Credits</span></div><div className="relationship-number"><strong>{item.values.capacity}</strong><span>Seats</span></div><span className={`table-status ${item.values.status.toLowerCase()}`}>{item.values.status}</span><Actions item={item} onEdit={onEdit} onDeactivate={onDeactivate}/></article>)}</section>; }
function TimetableBoard({ items, onEdit, onDeactivate }: LayoutProps) { const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]; return <section className="timetable-management">{days.map(day => { const rows = items.filter(x => x.values.dayOfWeek === day); return rows.length ? <article className="timetable-day panel" key={day}><div className="timetable-day-title"><span>{day.slice(0,3)}</span><h3>{day}</h3><small>{rows.length} classes</small></div><div className="timetable-slots">{rows.map(item => <div className="timetable-slot" key={item.id}><time>{item.values.startsAt}<span>–</span>{item.values.endsAt}</time><div><strong>{item.values.course}</strong><span>{item.values.department} · {item.values.teacher} · Room {item.values.classroom}</span></div><span className={`table-status ${item.values.status.toLowerCase()}`}>{item.values.status}</span><Actions item={item} onEdit={onEdit} onDeactivate={onDeactivate}/></div>)}</div></article> : null; })}</section>; }
function AttendanceDesk({ items, onEdit, onDeactivate }: LayoutProps) { return <section className="panel attendance-desk"><div className="attendance-desk-head"><span>Student</span><span>Department</span><span>Date & time</span><span>Method</span><span>Status</span><span>Actions</span></div>{items.map(item => <div className="attendance-desk-row" key={item.id}><div><span className="initial-chip">{initials(item.values.student)}</span><span><strong>{item.values.student}</strong><small>{item.values.number}</small></span></div><span>{item.values.department}</span><span>{item.values.date}<small>{item.values.checkedInAt || "No check-in"}</small></span><span>{item.values.method}</span><span className={`table-status ${item.values.status.toLowerCase()}`}>{item.values.status}</span><Actions item={item} onEdit={onEdit} onDeactivate={onDeactivate}/></div>)}</section>; }
function DepartmentDirectory({ items, references, onEdit, onDeactivate }: LayoutProps & { references: References }) { return <section className="panel horizontal-management-table department-horizontal"><div className="horizontal-management-head"><span>Code</span><span>Department</span><span>Head of department</span><span>Students</span><span>Teachers</span><span>Courses</span><span>Status</span><span>Actions</span></div>{items.map(item => { const head = references.teachers.find(x => x.id === item.values.headTeacherId); return <article className="horizontal-management-row" key={item.id}><div className="department-code-horizontal">{item.values.code}</div><div className="horizontal-primary"><strong>{item.values.name}</strong><span>Academic unit</span></div><div className="department-head-horizontal">{head?.values.photoDataUrl ? <Image unoptimized width={32} height={48} src={head.values.photoDataUrl} alt={`${item.values.head} profile`}/> : <span>{initials(item.values.head)}</span>}<div><strong>{item.values.head}</strong><small>{head?.values.email}</small></div></div><div className="relationship-number"><strong>{references.students.filter(x => x.values.departmentId === item.id).length}</strong><span>Active</span></div><div className="relationship-number"><strong>{references.teachers.filter(x => x.values.departmentId === item.id).length}</strong><span>Faculty</span></div><div className="relationship-number"><strong>{references.courses.filter(x => x.values.departmentId === item.id).length}</strong><span>Courses</span></div><span className={`table-status ${item.values.status.toLowerCase()}`}>{item.values.status}</span><Actions item={item} onEdit={onEdit} onDeactivate={onDeactivate}/></article>; })}</section>; }
function Gradebook({ items, onEdit, onDeactivate }: LayoutProps) { return <section className="panel gradebook"><div className="gradebook-head"><span>Student</span><span>Course</span><span>Department</span><span>Term</span><span>Score</span><span>Grade</span><span>Actions</span></div>{items.map(item => <div className="gradebook-row" key={item.id}><strong>{item.values.student}</strong><span>{item.values.course}</span><span>{item.values.department}</span><span>{item.values.term}</span><b>{item.values.score}%</b><span className={`grade-letter grade-${item.values.grade.toLowerCase()}`}>{item.values.grade}</span><Actions item={item} onEdit={onEdit} onDeactivate={onDeactivate}/></div>)}</section>; }
type LayoutProps = { items: CatalogItem[]; onEdit: (item: CatalogItem) => void; onDeactivate: (item: CatalogItem) => void };

function ManagementEditor({ module, item, references, scopeDepartmentId, onClose, onSaved }: { module: Exclude<Module, "overview">; item: CatalogItem | null; references: References; scopeDepartmentId: string; onClose: () => void; onSaved: () => void }) {
  const defaults = moduleDefaults(module, scopeDepartmentId); const [values, setValues] = useState<Record<string, string>>(item ? { ...defaults, ...item.values } : defaults); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const formFields = fields[module];
  function optionsFor(field: Field) {
    if (field.options) return field.options.map(value => ({ id: value, label: value }));
    if (!field.source) return [];
    let source = references[field.source];
    if (["teachers", "students", "classrooms", "courses"].includes(field.source) && values.departmentId) source = source.filter(option => option.values.departmentId === values.departmentId);
    return source.filter(option => option.values.status !== "Inactive").map(option => ({ id: option.id, label: option.values.name ?? option.values.code ?? option.values.student ?? option.values.course }));
  }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { if (item) await api.update(module, item.id, values); else await api.create(module, values); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save this record."); setSaving(false); } }
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><form className="modal management-modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">{item ? "Edit current data" : "New current data"}</span><h2>{item ? `Edit ${copy[module].singular}` : `Add ${copy[module].singular}`}</h2><p>Required relationships are validated before saving.</p></div><button type="button" className="icon-button" onClick={onClose}><Icon name="close"/></button></div><div className="management-form-grid">{formFields.map(field => <EditorField key={field.key} field={field} value={values[field.key] ?? ""} options={optionsFor(field)} onChange={value => setValues(current => ({ ...current, [field.key]: value }))}/>)}</div>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}>{saving ? "Saving relationships…" : item ? "Save changes" : `Add ${copy[module].singular}`}</button></div></form></div>;
}

function EditorField({ field, value, options, onChange }: { field: Field; value: string; options: { id: string; label: string }[]; onChange: (value: string) => void }) {
  if (field.type === "photo") return <label className="photo-upload-field"><span>{field.label}</span><div className="photo-upload-preview">{value ? <Image unoptimized width={120} height={180} src={value} alt="4 by 6 preview"/> : <div><Icon name="users" size={24}/><small>4 × 6</small></div>}</div><input type="file" accept="image/jpeg,image/png,image/webp" required={field.required && !value} onChange={async event => { const file = event.target.files?.[0]; if (file) onChange(await cropPhoto4x6(file)); }}/><b>Choose photo</b><small>JPG, PNG or WebP · cropped to 4×6</small></label>;
  if (field.type === "checkbox") return <label className="editor-checkbox"><input type="checkbox" checked={value === "true"} onChange={event => onChange(String(event.target.checked))}/><i/><span>{field.label}</span></label>;
  return <label className="editor-field"><span>{field.label}</span>{field.type === "select" ? <select required={field.required} value={value} onChange={event => onChange(event.target.value)}><option value="">Select {field.label.toLowerCase()}</option>{options.map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select> : <input required={field.required} type={field.type ?? "text"} step={field.key === "score" ? ".1" : undefined} min={field.key === "score" ? "0" : undefined} max={field.key === "score" ? "100" : undefined} value={value} onChange={event => onChange(event.target.value)}/>}</label>;
}

function moduleDefaults(module: Exclude<Module, "overview">, departmentId: string): Record<string, string> { const today = new Date().toISOString().slice(0,10); const base = { departmentId }; return module === "students" ? { ...base, year: "1", status: "Active" } : module === "teachers" ? { ...base, status: "Available" } : module === "classrooms" ? { ...base, capacity: "40", status: "Available", deviceOnline: "true" } : module === "courses" ? { ...base, credits: "3", capacity: "40", status: "Active" } : module === "timetable" ? { ...base, dayOfWeek: "Monday", startsAt: "08:00", endsAt: "09:00", status: "Upcoming" } : module === "attendance" ? { ...base, date: today, status: "Present", method: "ID Card" } : module === "departments" ? { status: "Active" } : { ...base, term: "Semester 1", score: "80" }; }
function initials(name = "") { return name.split(" ").filter(Boolean).slice(0,2).map(part => part[0]).join("").toUpperCase(); }
async function cropPhoto4x6(file: File): Promise<string> { const source = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); const image = await new Promise<HTMLImageElement>((resolve, reject) => { const value = document.createElement("img"); value.onload = () => resolve(value); value.onerror = reject; value.src = source; }); const canvas = document.createElement("canvas"); canvas.width = 400; canvas.height = 600; const context = canvas.getContext("2d"); if (!context) return source; const targetRatio = 2 / 3; const sourceRatio = image.width / image.height; let sx = 0, sy = 0, sw = image.width, sh = image.height; if (sourceRatio > targetRatio) { sw = image.height * targetRatio; sx = (image.width - sw) / 2; } else { sh = image.width / targetRatio; sy = (image.height - sh) / 2; } context.drawImage(image, sx, sy, sw, sh, 0, 0, 400, 600); return canvas.toDataURL("image/jpeg", .84); }
